---

- name: Deploy password file
  copy:
    content: '{{ vault_repo_password }}'
    dest: '/var/lib/restic/repopw'
    mode: '0600'
    owner: 'root'
    group: 'root'
  no_log: true
  ignore_errors: true
