---

- name: Deploy password file
  copy:
    content: '{{ restic_repo_password }}'
    dest: '{{ restic_password_file }}'
    mode: '0600'
    owner: 'root'
    group: 'root'
  no_log: true
  ignore_errors: true
