---
# vi: set ft=ansible :

- name: Install restic
  include_tasks: install.yml
  tags:
    - restic
    - install

- name: Configure restic
  include_tasks: configure.yml
  tags:
    - restic
    - configure

- name: Initialize repo
  include_tasks: initrepo.yml
  when: restic_init_repo | bool
  tags:
    - restic
    - configure

- name: Add cronjobs
  include_tasks: cron.yml
  tags:
    - restic
    - configure
    - cron
